# Site
name: "나무의 노트"
title: "나무의 노트"
description: "1인 대학생 개발자, 나무"
logo: 'assets/images/base/icon.png'
favicon: 'assets/images/base/icon.png'
baseurl:
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'https-namooplus-github-io'
include: ["_pages"]
permalink: /:title/
email: namoo.developer@gmail.com

# Authors
authors:
  namoo:
    name: 나무
    display_name: 나무
    email: namoo.developer@gmail.com
    instagram: https://www.instagram.com/min.i.stop/
    github: https://github.com/namooplus
    description: "1인 대학생 개발자, 나무입니다."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
