# Site settings
title:          "나무의 노트"
description:    "1인 대학생 개발자, 나무"
url:            "https://namooplus.github.io/"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         나무
  url:          https://namooplus.github.io/
  email:        namoo.developer@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale
